const $=id=>document.getElementById(id);let s=JSON.parse(localStorage.getItem('jm_airtime')||'null')||{logged:false,balance:10000,history:[]};let signup=false;
const money=n=>'₦'+Number(n).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2});
function save(){localStorage.setItem('jm_airtime',JSON.stringify(s));render()}function msg(x){$('toast').textContent=x;$('toast').style.display='block';setTimeout(()=>{$('toast').style.display='none'},2200)}
function render(){$('auth').classList.toggle('hidden',s.logged);$('app').classList.toggle('hidden',!s.logged);$('logout').classList.toggle('hidden',!s.logged);$('balance').textContent=money(s.balance);$('walletBalance').textContent=money(s.balance);$('transactions').innerHTML=s.history.length?s.history.map(x=>`<div class="history"><b>${x.type}</b><br><span class="muted">${x.details}</span><br>${money(x.amount)}</div>`).join(''):'<p class="muted">No transactions yet.</p>'}
function nav(p){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(p).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}
$('authBtn').onclick=()=>{if(!$('email').value||!$('password').value||(signup&&!$('name').value))return msg('Please fill in all fields.');s.logged=true;save();msg(signup?'Account created.':'Logged in.')};
$('switch').onclick=()=>{signup=!signup;$('authTitle').textContent=signup?'Create an account':'Welcome back';$('authBtn').textContent=signup?'Sign up':'Log in';$('switch').textContent=signup?'Already have an account? Log in':'Create an account';$('name').classList.toggle('hidden',!signup)};
$('logout').onclick=()=>{s.logged=false;save()};function fund(){s.balance+=5000;s.history.unshift({type:'Wallet top-up',details:'Demo wallet credit',amount:5000});save();msg('₦5,000 added to wallet.')}$('fund').onclick=fund;$('fund2').onclick=fund;
$('buyAirtime').onclick=()=>{let p=$('aPhone').value.trim(),a=Number($('aAmount').value);if(!p||!a||a<50)return msg('Enter a valid phone number and amount.');if(a>s.balance)return msg('Insufficient wallet balance.');s.balance-=a;s.history.unshift({type:'Airtime',details:`${$('aNetwork').value} • ${p}`,amount:-a});save();msg('Airtime purchase recorded.')};
$('buyData').onclick=()=>{let p=$('dPhone').value.trim(),a=Number($('dPlan').value);if(!p)return msg('Enter a phone number.');if(a>s.balance)return msg('Insufficient wallet balance.');s.balance-=a;s.history.unshift({type:'Data',details:`${$('dNetwork').value} • ${p}`,amount:-a});save();msg('Data purchase recorded.')};
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>nav(x.dataset.page));document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>nav(x.dataset.go));render();
